export const dynamicSearchRequest = {
  StartRow: 0,
  EndRow: 10,
  ExcludeCatalogSearch: true,
  ExtensionData: null,
  IsFacetSearchRequired: false,
  IsKeysSearch: false,
  IsNewProductRequired: false,
  IsOnlyItemList: true,
  IsPromoProductRequired: false,
  IsVINSearch: false,
  Search: "*",
  SortBy: "score desc",
  SubSearch: "",
  TAG: null,
  ApplicationFilter: [],
  CatalogFilter: [],
  PriceFilter: [],
  SupplierFilter: [],
};
